import { User, Project, Section, Task, Notification } from "@/types";

// Helper: compute an ISO date string offset from now by N days
function daysFromNow(n: number): string {
  return new Date(Date.now() + n * 86400000).toISOString();
}

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const mockUsers: User[] = [
  { id: "demo-user", name: "Demo User", email: "demo@adana.app", avatar: null },
  { id: "user-2", name: "Sarah Chen", email: "sarah@adana.app", avatar: null },
  { id: "user-3", name: "Alex Johnson", email: "alex@adana.app", avatar: null },
];

export const mockCurrentUser: User = mockUsers[0];

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

export const mockProjects: Project[] = [
  {
    id: "project-website",
    name: "Website Redesign",
    description: "Redesign the company website with a modern look and feel",
    color: "#4c6ef5",
    icon: "globe",
    archived: false,
    favorite: true,
    defaultView: "list",
    creatorId: "demo-user",
    teamId: "team-engineering",
  },
  {
    id: "project-mobile",
    name: "Mobile App v2",
    description: "Build version 2 of the mobile application",
    color: "#51cf66",
    icon: "smartphone",
    archived: false,
    favorite: false,
    defaultView: "list",
    creatorId: "demo-user",
    teamId: "team-engineering",
  },
  {
    id: "project-marketing",
    name: "Q2 Marketing Campaign",
    description: "Plan and execute Q2 marketing initiatives",
    color: "#ff6b6b",
    icon: "megaphone",
    archived: false,
    favorite: false,
    defaultView: "list",
    creatorId: "user-2",
    teamId: "team-engineering",
  },
];

// ---------------------------------------------------------------------------
// Sections  (for project-website)
// ---------------------------------------------------------------------------

export const mockSections: Section[] = [
  { id: "section-todo", name: "To Do", position: 0, projectId: "project-website" },
  { id: "section-inprogress", name: "In Progress", position: 1, projectId: "project-website" },
  { id: "section-review", name: "In Review", position: 2, projectId: "project-website" },
  { id: "section-done", name: "Done", position: 3, projectId: "project-website" },
];

// ---------------------------------------------------------------------------
// Tasks  (9 tasks matching the seed data)
// ---------------------------------------------------------------------------

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Design new homepage mockup",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(2),
    dueTime: null,
    startDate: null,
    priority: "high",
    taskType: "task",
    approvalStatus: null,
    position: 0,
    isTemplate: false,
    assigneeId: "user-2",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-inprogress",
    parentId: null,
  },
  {
    id: "task-2",
    title: "Implement responsive navigation",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(5),
    dueTime: null,
    startDate: null,
    priority: "medium",
    taskType: "task",
    approvalStatus: null,
    position: 1,
    isTemplate: false,
    assigneeId: "user-3",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-todo",
    parentId: null,
  },
  {
    id: "task-3",
    title: "Set up CI/CD pipeline",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(1),
    dueTime: null,
    startDate: null,
    priority: "high",
    taskType: "task",
    approvalStatus: null,
    position: 2,
    isTemplate: false,
    assigneeId: "demo-user",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-review",
    parentId: null,
  },
  {
    id: "task-4",
    title: "Write API documentation",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(7),
    dueTime: null,
    startDate: null,
    priority: "low",
    taskType: "task",
    approvalStatus: null,
    position: 3,
    isTemplate: false,
    assigneeId: "user-2",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-todo",
    parentId: null,
  },
  {
    id: "task-5",
    title: "Performance optimization audit",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(3),
    dueTime: null,
    startDate: null,
    priority: "medium",
    taskType: "task",
    approvalStatus: null,
    position: 4,
    isTemplate: false,
    assigneeId: "demo-user",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-todo",
    parentId: null,
  },
  {
    id: "task-6",
    title: "User testing sessions",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(4),
    dueTime: null,
    startDate: null,
    priority: "high",
    taskType: "milestone",
    approvalStatus: null,
    position: 5,
    isTemplate: false,
    assigneeId: "user-3",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-inprogress",
    parentId: null,
  },
  {
    id: "task-7",
    title: "Final design approval",
    description: null,
    completed: false,
    completedAt: null,
    dueDate: daysFromNow(6),
    dueTime: null,
    startDate: null,
    priority: "high",
    taskType: "approval",
    approvalStatus: "pending",
    position: 6,
    isTemplate: false,
    assigneeId: "demo-user",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-review",
    parentId: null,
  },
  {
    id: "task-8",
    title: "Deploy to staging",
    description: null,
    completed: true,
    completedAt: daysFromNow(-1),
    dueDate: null,
    dueTime: null,
    startDate: null,
    priority: "medium",
    taskType: "task",
    approvalStatus: null,
    position: 7,
    isTemplate: false,
    assigneeId: "demo-user",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-done",
    parentId: null,
  },
  {
    id: "task-9",
    title: "Create style guide",
    description: null,
    completed: true,
    completedAt: daysFromNow(-2),
    dueDate: null,
    dueTime: null,
    startDate: null,
    priority: "low",
    taskType: "task",
    approvalStatus: null,
    position: 8,
    isTemplate: false,
    assigneeId: "user-2",
    creatorId: "demo-user",
    projectId: "project-website",
    sectionId: "section-done",
    parentId: null,
  },
];

// ---------------------------------------------------------------------------
// Notifications  (3 items matching the seed)
// ---------------------------------------------------------------------------

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "assigned",
    title: "New task assigned",
    message: "You've been assigned 'Set up CI/CD pipeline'",
    read: false,
    archived: false,
    userId: "demo-user",
    linkUrl: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "notif-2",
    type: "commented",
    title: "New comment",
    message: "Sarah commented on 'Design new homepage mockup'",
    read: false,
    archived: false,
    userId: "demo-user",
    linkUrl: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "notif-3",
    type: "completed",
    title: "Task completed",
    message: "Alex completed 'Deploy to staging'",
    read: false,
    archived: false,
    userId: "demo-user",
    linkUrl: null,
    createdAt: new Date().toISOString(),
  },
];
