ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ooo_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ooo_from TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ooo_until TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ooo_message TEXT;
